version: "3.7"

networks:
  proxy:
    external: true

volumes:
  purchasing-db:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/db
  purchasing-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/data

services:
  db:
    image: postgres:13-alpine
    container_name: purchasing-db
    restart: unless-stopped
    env_file: ./.env
    volumes:
      - purchasing-db:/var/lib/postgresql/data
    networks:
      - proxy
  web:
    image: pcdworks/purchasing:latest
    container_name: purchasing
    restart: unless-stopped
    volumes:
      - purchasing-data:/app/storage
    env_file: ./.env
    networks:
      - proxy
    labels:
      caddy: "${CADDY_DOMAIN}"
      caddy.tls: internal
      caddy.0_reverse_proxy: "{{upstreams 3000}}"
      caddy.0_reverse_proxy.header_up: X-Real-IP {remote_host}
    depends_on:
      - db
