version: "3.7"

networks:
  proxy:
    external: true

volumes:
  purchasing-db:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/db
  purchasing-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/data
  purchasing-style:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/style

services:
  db:
    image: postgres:13-alpine
    container_name: purchasing-db
    restart: unless-stopped
    env_file: ./.env
    volumes:
      - purchasing-db:/var/lib/postgresql/data
    networks:
      - proxy
  web:
    image: pcdworks/purchasing:latest
    container_name: purchasing
    restart: unless-stopped
    volumes:
      - purchasing-data:/app/storage
      - purchasing-style:/app/public/style
    env_file: ./.env
    networks:
      - proxy
    labels:
      com.centurylinklabs.watchtower.enable: false
      caddy: "${CADDY_DOMAIN}"
      caddy.reverse_proxy: "{{upstreams 3000}}"
    depends_on:
      - db
